#! /usr/bin/env python3
import http.client
import os
import datetime
import base64

#attachment encoding
with open('../log.txt','rb') as f:
    data = f.read()
    f.close()

attachment = base64.b64encode(data)

conn = http.client.HTTPSConnection("api.sendgrid.com")

print (os.environ["email"])
payload = "{\"personalizations\":[{\"to\":[{\"email\":\"" + os.environ["email"] + "\"}],\"subject\":\"We are Sorry\"}],\"from\":{\"email\":\"xeon.harsh@gmail.com\",\"name\":\"LinuInator\"},\"reply_to\":{\"email\":\"xeon.harsh@gmail.com\",\"name\":\"Meilix Generator\"},\"subject\":\"We are Sorry\",\"content\":[{\"type\":\"text/html\",\"value\":\"<html><p>Hi,<br>Your Build Gave error please report it to the developer<br><br>Thank You,<br>LinuxInator Team</p></html>\"}],\"attachments\":[{\"content\":\""+str(attachment)[2:-1]+"\",\"type\":\"text/plain\",\"filename\":\"log.txt\"}]}"

print (type(payload))

authorization = "Bearer " + os.environ["mail_api_key"]

headers = {
    'authorization': authorization,
    'content-type': "application/json"
    }

conn.request("POST", "/v3/mail/send", payload, headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))
